/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *	   Sam Padgett	       - initial API and implementation
 *     Michael Fiedler     - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Matthieu Helleboid   - Support for multiple Service Providers.
 *     Anass Radouani       - Support for multiple Service Providers.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package hu.bme.mit.papyrus.oslc.adaptor.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;
import javax.servlet.http.HttpServletRequest;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import javax.ws.rs.core.UriBuilder;

import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

import hu.bme.mit.papyrus.oslc.adaptor.servlet.ServletListener; 
import hu.bme.mit.papyrus.oslc.adaptor.PapyrusRequirementProviderConstants;
import hu.bme.mit.papyrus.oslc.adaptor.resources.Person;	
import hu.bme.mit.papyrus.oslc.adaptor.resources.Person;	
import hu.bme.mit.papyrus.oslc.adaptor.resources.Type;	

// Start of user code imports
// End of user code

@OslcNamespace(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE)
@OslcName(PapyrusRequirementProviderConstants.REQUIREMENTCOLLECTION) 
@OslcResourceShape(title = "RequirementCollection Resource Shape", describes = PapyrusRequirementProviderConstants.TYPE_REQUIREMENTCOLLECTION)
public class RequirementCollection
	extends AbstractResource
	implements IRequirementCollection
{

private String title;  
private String description;  
private String identifier;  
private String shortTitle;  
private HashSet<String> subject = new HashSet<String>();  
private HashSet<Person> creator = new HashSet<Person>();  
private HashSet<Person> contributor = new HashSet<Person>();  
private Date created;  
private Date modified;  
private HashSet<Type> type = new HashSet<Type>();  
private URI serviceProvider;  
private Link instanceShape = new Link();  
private HashSet<Link> uses = new HashSet<Link>();  
private HashSet<Link> elaboratedBy = new HashSet<Link>();  
private HashSet<Link> elaborates = new HashSet<Link>();  
private HashSet<Link> specifiedBy = new HashSet<Link>();  
private HashSet<Link> specifies = new HashSet<Link>();  
private HashSet<Link> affectedBy = new HashSet<Link>();  
private HashSet<Link> trackedBy = new HashSet<Link>();  
private HashSet<Link> implementedBy = new HashSet<Link>();  
private HashSet<Link> validatedBy = new HashSet<Link>();  
private HashSet<Link> satisfiedBy = new HashSet<Link>();  
private HashSet<Link> satisfies = new HashSet<Link>();  
private HashSet<Link> decomposedBy = new HashSet<Link>();  
private HashSet<Link> decomposes = new HashSet<Link>();  
private HashSet<Link> constrainedBy = new HashSet<Link>();  
private HashSet<Link> constrains = new HashSet<Link>();  

public RequirementCollection()
       throws URISyntaxException
{
    super();

	// Start of user code constructor1
	// End of user code
}

public RequirementCollection(final URI about)
       throws URISyntaxException
{
    super(about);

	// Start of user code constructor2
	// End of user code
}

public RequirementCollection(final String serviceProviderId, final String requirementCollectionId)
       throws URISyntaxException
{
	this (constructURI(serviceProviderId, requirementCollectionId));
	// Start of user code constructor3
	// End of user code
}
public static URI constructURI(final String serviceProviderId, final String requirementCollectionId)
{
    String basePath = ServletListener.getServicesBase();
    Map<String, Object> pathParameters = new HashMap<String, Object>();
    pathParameters.put("serviceProviderId", serviceProviderId);
    pathParameters.put("requirementCollectionId", requirementCollectionId);
    String instanceURI = "Requirement_ServiceProvider/{serviceProviderId}/service1/requirementCollections/{requirementCollectionId}";
  
    final UriBuilder builder = UriBuilder.fromUri(basePath);
    return builder.path(instanceURI).buildFromMap(pathParameters);
}

public static Link constructLink(final String serviceProviderId, final String requirementCollectionId , final String label)
{
	return new Link(constructURI(serviceProviderId, requirementCollectionId), label);
}

public static Link constructLink(final String serviceProviderId, final String requirementCollectionId)
{
	return new Link(constructURI(serviceProviderId, requirementCollectionId));
}

public String toString()
{
	return toString(false);
}

public String toString(boolean asLocalResource)
{
		String result = "";
		// Start of user code toString_init
		// End of user code

		if (asLocalResource) {
			result = result + "{a Local RequirementCollection Resource} - update RequirementCollection.toString() to present resource as desired.";
			// Start of user code toString_bodyForLocalResource
			// End of user code
		}
		else {
			result = getAbout().toString();
		}

		// Start of user code toString_finalize
		// End of user code

		return result;
}

public String toHtml()
{
	return toHtml(false);
}

public String toHtml(boolean asLocalResource)
{
		String result = "";
		// Start of user code toHtml_init
		// End of user code

		if (asLocalResource) {
			result = toString(true);
			// Start of user code toHtml_bodyForLocalResource
			// End of user code
		}
		else {
			result = "<a href=\"" + getAbout() + "\">" + toString() + "</a>";
		}

		// Start of user code toHtml_finalize
		// End of user code

		return result;
}

    public void addSubject(final String subject )
    {
        this.subject.add(subject);
    }
    public void addCreator(final Person creator )
    {
        this.creator.add(creator);
    }
    public void addContributor(final Person contributor )
    {
        this.contributor.add(contributor);
    }
    public void addType(final Type type )
    {
        this.type.add(type);
    }
    public void addUses(final Link uses )
    {
        this.uses.add(uses);
    }
    public void addElaboratedBy(final Link elaboratedBy )
    {
        this.elaboratedBy.add(elaboratedBy);
    }
    public void addElaborates(final Link elaborates )
    {
        this.elaborates.add(elaborates);
    }
    public void addSpecifiedBy(final Link specifiedBy )
    {
        this.specifiedBy.add(specifiedBy);
    }
    public void addSpecifies(final Link specifies )
    {
        this.specifies.add(specifies);
    }
    public void addAffectedBy(final Link affectedBy )
    {
        this.affectedBy.add(affectedBy);
    }
    public void addTrackedBy(final Link trackedBy )
    {
        this.trackedBy.add(trackedBy);
    }
    public void addImplementedBy(final Link implementedBy )
    {
        this.implementedBy.add(implementedBy);
    }
    public void addValidatedBy(final Link validatedBy )
    {
        this.validatedBy.add(validatedBy);
    }
    public void addSatisfiedBy(final Link satisfiedBy )
    {
        this.satisfiedBy.add(satisfiedBy);
    }
    public void addSatisfies(final Link satisfies )
    {
        this.satisfies.add(satisfies);
    }
    public void addDecomposedBy(final Link decomposedBy )
    {
        this.decomposedBy.add(decomposedBy);
    }
    public void addDecomposes(final Link decomposes )
    {
        this.decomposes.add(decomposes);
    }
    public void addConstrainedBy(final Link constrainedBy )
    {
        this.constrainedBy.add(constrainedBy);
    }
    public void addConstrains(final Link constrains )
    {
        this.constrains.add(constrains);
    }

	@OslcName("title")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "title")
	@OslcDescription("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element. ")
	@OslcOccurs(Occurs.ExactlyOne)
	@OslcValueType(ValueType.XMLLiteral)
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getTitle()
    {
        return title;
    }

	@OslcName("description")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "description")
	@OslcDescription("Descriptive text about resource represented as rich text in XHTML content. SHOULD include only content that is valid and suitable inside an XHTML <div> element. ")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.XMLLiteral)
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getDescription()
    {
        return description;
    }

	@OslcName("identifier")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "identifier")
	@OslcDescription("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
	@OslcOccurs(Occurs.ExactlyOne)
	@OslcValueType(ValueType.String)
	@OslcReadOnly(true)
	@OslcTitle("")
    public String getIdentifier()
    {
        return identifier;
    }

	@OslcName("shortTitle")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.OSLC_CORE_NAMSPACE + "shortTitle")
	@OslcDescription("Shorter form of dcterms:title for the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.XMLLiteral)
	@OslcReadOnly(false)
	@OslcTitle("")
    public String getShortTitle()
    {
        return shortTitle;
    }

	@OslcName("subject")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "subject")
	@OslcDescription("Tag or keyword for a resource. Each occurrence of a dcterms:subject property denotes an additional tag for the resource.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.String)
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<String> getSubject()
    {
        return subject;
    }

	@OslcName("creator")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "creator")
	@OslcDescription("Creator or creators of resource (reference: Dublin Core). It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.LocalResource)
	@OslcRange({PapyrusRequirementProviderConstants.TYPE_PERSON})
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Person> getCreator()
    {
        return creator;
    }

	@OslcName("contributor")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "contributor")
	@OslcDescription("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case. ")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.LocalResource)
	@OslcRange({PapyrusRequirementProviderConstants.TYPE_PERSON})
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Person> getContributor()
    {
        return contributor;
    }

	@OslcName("created")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "created")
	@OslcDescription("Timestamp of resource creation")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.DateTime)
	@OslcReadOnly(true)
	@OslcTitle("")
    public Date getCreated()
    {
        return created;
    }

	@OslcName("modified")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "modified")
	@OslcDescription("Timestamp last latest resource modification")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.DateTime)
	@OslcReadOnly(true)
	@OslcTitle("")
    public Date getModified()
    {
        return modified;
    }

	@OslcName("type")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.DUBLIN_CORE_NAMSPACE + "type")
	@OslcDescription("A short string representation for the type, example 'Defect'.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.LocalResource)
	@OslcRange({PapyrusRequirementProviderConstants.TYPE_TYPE})
	@OslcReadOnly(false)
	@OslcTitle("")
    public HashSet<Type> getType()
    {
        return type;
    }

	@OslcName("serviceProvider")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.OSLC_CORE_NAMSPACE + "serviceProvider")
	@OslcDescription("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property. ")
	@OslcOccurs(Occurs.ExactlyOne)
	@OslcReadOnly(false)
	@OslcTitle("")
    public URI getServiceProvider()
    {
        return serviceProvider;
    }

	@OslcName("instanceShape")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.OSLC_CORE_NAMSPACE + "instanceShape")
	@OslcDescription("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
	@OslcOccurs(Occurs.ZeroOrOne)
	@OslcValueType(ValueType.Resource)
	@OslcReadOnly(false)
	@OslcTitle("")
    public Link getInstanceShape()
    {
        return instanceShape;
    }

	@OslcName("uses")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "uses")
	@OslcDescription("A collection uses a resource - the resource is in the requirement collection.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getUses()
    {
        return uses;
    }

	@OslcName("elaboratedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "elaboratedBy")
	@OslcDescription("The subject is elaborated by the object. For example, a user requirement is elaborated by use case. ")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getElaboratedBy()
    {
        return elaboratedBy;
    }

	@OslcName("elaborates")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "elaborates")
	@OslcDescription("The object is elaborated by the subject.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getElaborates()
    {
        return elaborates;
    }

	@OslcName("specifiedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "specifiedBy")
	@OslcDescription("The subject is specified by the object. For example, a requirement is elaborated by a model element .")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getSpecifiedBy()
    {
        return specifiedBy;
    }

	@OslcName("specifies")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "specifies")
	@OslcDescription("The object is specified by the subject.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getSpecifies()
    {
        return specifies;
    }

	@OslcName("affectedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "affectedBy")
	@OslcDescription("Requirement is affected by a resource, such as a defect or issue.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getAffectedBy()
    {
        return affectedBy;
    }

	@OslcName("trackedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "trackedBy")
	@OslcDescription("Resource, such as a change request, which tracks this requirement.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getTrackedBy()
    {
        return trackedBy;
    }

	@OslcName("implementedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "implementedBy")
	@OslcDescription("Resource, such as a change request, which implements this requirement.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getImplementedBy()
    {
        return implementedBy;
    }

	@OslcName("validatedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "validatedBy")
	@OslcDescription("Resource, such as a test case, which validates this requirement.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getValidatedBy()
    {
        return validatedBy;
    }

	@OslcName("satisfiedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "satisfiedBy")
	@OslcDescription("The subject is satisfied by the object. For example, a user requirement is satisfied by a system requirement. ")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getSatisfiedBy()
    {
        return satisfiedBy;
    }

	@OslcName("satisfies")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "satisfies")
	@OslcDescription("The object is satisfied by the subject.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getSatisfies()
    {
        return satisfies;
    }

	@OslcName("decomposedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "decomposedBy")
	@OslcDescription("The subject is decomposed by the object. For example, a system requirement is decomposed into a collection of system requirements.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getDecomposedBy()
    {
        return decomposedBy;
    }

	@OslcName("decomposes")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "decomposes")
	@OslcDescription("The object is decomposed by the subject.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getDecomposes()
    {
        return decomposes;
    }

	@OslcName("constrainedBy")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "constrainedBy")
	@OslcDescription("The subject is constrained by the object. For example, a functional requirement is constrained by a safety requirement.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getConstrainedBy()
    {
        return constrainedBy;
    }

	@OslcName("constrains")
	@OslcPropertyDefinition(PapyrusRequirementProviderConstants.REQUIREMENT_MANAGEMENT_NAMSPACE + "constrains")
	@OslcDescription("The object is constrained by the subject.")
	@OslcOccurs(Occurs.ZeroOrMany)
	@OslcValueType(ValueType.Resource)
	@OslcRepresentation(Representation.Reference)
	@OslcReadOnly(false)
    public HashSet<Link> getConstrains()
    {
        return constrains;
    }


    public void setTitle(final String title )
    {
        this.title = title;
    }
    public void setDescription(final String description )
    {
        this.description = description;
    }
    public void setIdentifier(final String identifier )
    {
        this.identifier = identifier;
    }
    public void setShortTitle(final String shortTitle )
    {
        this.shortTitle = shortTitle;
    }
    public void setSubject(final HashSet<String> subject )
    {
        this.subject.clear();
        if (subject != null)
        {
            this.subject.addAll(subject);
        }

    }
    public void setCreator(final HashSet<Person> creator )
    {
        this.creator.clear();
        if (creator != null)
        {
            this.creator.addAll(creator);
        }

    }
    public void setContributor(final HashSet<Person> contributor )
    {
        this.contributor.clear();
        if (contributor != null)
        {
            this.contributor.addAll(contributor);
        }

    }
    public void setCreated(final Date created )
    {
        this.created = created;
    }
    public void setModified(final Date modified )
    {
        this.modified = modified;
    }
    public void setType(final HashSet<Type> type )
    {
        this.type.clear();
        if (type != null)
        {
            this.type.addAll(type);
        }

    }
    public void setServiceProvider(final URI serviceProvider )
    {
        this.serviceProvider = serviceProvider;
    }
    public void setInstanceShape(final Link instanceShape )
    {
        this.instanceShape = instanceShape;
    }
    public void setUses(final HashSet<Link> uses )
    {
        this.uses.clear();
        if (uses != null)
        {
            this.uses.addAll(uses);
        }

    }
    public void setElaboratedBy(final HashSet<Link> elaboratedBy )
    {
        this.elaboratedBy.clear();
        if (elaboratedBy != null)
        {
            this.elaboratedBy.addAll(elaboratedBy);
        }

    }
    public void setElaborates(final HashSet<Link> elaborates )
    {
        this.elaborates.clear();
        if (elaborates != null)
        {
            this.elaborates.addAll(elaborates);
        }

    }
    public void setSpecifiedBy(final HashSet<Link> specifiedBy )
    {
        this.specifiedBy.clear();
        if (specifiedBy != null)
        {
            this.specifiedBy.addAll(specifiedBy);
        }

    }
    public void setSpecifies(final HashSet<Link> specifies )
    {
        this.specifies.clear();
        if (specifies != null)
        {
            this.specifies.addAll(specifies);
        }

    }
    public void setAffectedBy(final HashSet<Link> affectedBy )
    {
        this.affectedBy.clear();
        if (affectedBy != null)
        {
            this.affectedBy.addAll(affectedBy);
        }

    }
    public void setTrackedBy(final HashSet<Link> trackedBy )
    {
        this.trackedBy.clear();
        if (trackedBy != null)
        {
            this.trackedBy.addAll(trackedBy);
        }

    }
    public void setImplementedBy(final HashSet<Link> implementedBy )
    {
        this.implementedBy.clear();
        if (implementedBy != null)
        {
            this.implementedBy.addAll(implementedBy);
        }

    }
    public void setValidatedBy(final HashSet<Link> validatedBy )
    {
        this.validatedBy.clear();
        if (validatedBy != null)
        {
            this.validatedBy.addAll(validatedBy);
        }

    }
    public void setSatisfiedBy(final HashSet<Link> satisfiedBy )
    {
        this.satisfiedBy.clear();
        if (satisfiedBy != null)
        {
            this.satisfiedBy.addAll(satisfiedBy);
        }

    }
    public void setSatisfies(final HashSet<Link> satisfies )
    {
        this.satisfies.clear();
        if (satisfies != null)
        {
            this.satisfies.addAll(satisfies);
        }

    }
    public void setDecomposedBy(final HashSet<Link> decomposedBy )
    {
        this.decomposedBy.clear();
        if (decomposedBy != null)
        {
            this.decomposedBy.addAll(decomposedBy);
        }

    }
    public void setDecomposes(final HashSet<Link> decomposes )
    {
        this.decomposes.clear();
        if (decomposes != null)
        {
            this.decomposes.addAll(decomposes);
        }

    }
    public void setConstrainedBy(final HashSet<Link> constrainedBy )
    {
        this.constrainedBy.clear();
        if (constrainedBy != null)
        {
            this.constrainedBy.addAll(constrainedBy);
        }

    }
    public void setConstrains(final HashSet<Link> constrains )
    {
        this.constrains.clear();
        if (constrains != null)
        {
            this.constrains.addAll(constrains);
        }

    }

    static public String titleToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:titleToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"title\">title: </LABEL>";
    
    	// Start of user code "Mid:titleToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"title\" type=\"text\" style=\"width: 400px\" id=\"title\" >";
    	// Start of user code "Finalize:titleToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String descriptionToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:descriptionToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"description\">description: </LABEL>";
    
    	// Start of user code "Mid:descriptionToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"description\" type=\"text\" style=\"width: 400px\" id=\"description\" >";
    	// Start of user code "Finalize:descriptionToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String identifierToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:identifierToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"identifier\">identifier: </LABEL>";
    
    	// Start of user code "Mid:identifierToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"identifier\" type=\"text\" style=\"width: 400px\" id=\"identifier\" >";
    	// Start of user code "Finalize:identifierToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String shortTitleToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:shortTitleToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"shortTitle\">shortTitle: </LABEL>";
    
    	// Start of user code "Mid:shortTitleToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"shortTitle\" type=\"text\" style=\"width: 400px\" id=\"shortTitle\" >";
    	// Start of user code "Finalize:shortTitleToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String subjectToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:subjectToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"subject\">subject: </LABEL>";
    
    	// Start of user code "Mid:subjectToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"subject\" type=\"text\" style=\"width: 400px\" id=\"subject\" >";
    	// Start of user code "Finalize:subjectToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String creatorToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:creatorToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"creator\">creator: </LABEL>";
    
    	// Start of user code "Mid:creatorToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:creatorToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String contributorToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:contributorToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"contributor\">contributor: </LABEL>";
    
    	// Start of user code "Mid:contributorToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:contributorToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String createdToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:createdToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"created\">created: </LABEL>";
    
    	// Start of user code "Mid:createdToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"created\" type=\"text\" style=\"width: 400px\" id=\"created\" >";
    	// Start of user code "Finalize:createdToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String modifiedToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:modifiedToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"modified\">modified: </LABEL>";
    
    	// Start of user code "Mid:modifiedToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"modified\" type=\"text\" style=\"width: 400px\" id=\"modified\" >";
    	// Start of user code "Finalize:modifiedToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String typeToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:typeToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"type\">type: </LABEL>";
    
    	// Start of user code "Mid:typeToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:typeToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String serviceProviderToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:serviceProviderToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"serviceProvider\">serviceProvider: </LABEL>";
    
    	// Start of user code "Mid:serviceProviderToHtmlForCreation(...)"
    	// End of user code
    
    	s= s + "<input name=\"serviceProvider\" type=\"text\" style=\"width: 400px\" id=\"serviceProvider\" >";
    	// Start of user code "Finalize:serviceProviderToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String instanceShapeToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:instanceShapeToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"instanceShape\">instanceShape: </LABEL>";
    
    	// Start of user code "Mid:instanceShapeToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:instanceShapeToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String usesToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:usesToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"uses\">uses: </LABEL>";
    
    	// Start of user code "Mid:usesToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:usesToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String elaboratedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:elaboratedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"elaboratedBy\">elaboratedBy: </LABEL>";
    
    	// Start of user code "Mid:elaboratedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:elaboratedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String elaboratesToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:elaboratesToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"elaborates\">elaborates: </LABEL>";
    
    	// Start of user code "Mid:elaboratesToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:elaboratesToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String specifiedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:specifiedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"specifiedBy\">specifiedBy: </LABEL>";
    
    	// Start of user code "Mid:specifiedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:specifiedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String specifiesToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:specifiesToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"specifies\">specifies: </LABEL>";
    
    	// Start of user code "Mid:specifiesToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:specifiesToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String affectedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:affectedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"affectedBy\">affectedBy: </LABEL>";
    
    	// Start of user code "Mid:affectedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:affectedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String trackedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:trackedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"trackedBy\">trackedBy: </LABEL>";
    
    	// Start of user code "Mid:trackedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:trackedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String implementedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:implementedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"implementedBy\">implementedBy: </LABEL>";
    
    	// Start of user code "Mid:implementedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:implementedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String validatedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:validatedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"validatedBy\">validatedBy: </LABEL>";
    
    	// Start of user code "Mid:validatedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:validatedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String satisfiedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:satisfiedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"satisfiedBy\">satisfiedBy: </LABEL>";
    
    	// Start of user code "Mid:satisfiedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:satisfiedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String satisfiesToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:satisfiesToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"satisfies\">satisfies: </LABEL>";
    
    	// Start of user code "Mid:satisfiesToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:satisfiesToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String decomposedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:decomposedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"decomposedBy\">decomposedBy: </LABEL>";
    
    	// Start of user code "Mid:decomposedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:decomposedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String decomposesToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:decomposesToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"decomposes\">decomposes: </LABEL>";
    
    	// Start of user code "Mid:decomposesToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:decomposesToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String constrainedByToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:constrainedByToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"constrainedBy\">constrainedBy: </LABEL>";
    
    	// Start of user code "Mid:constrainedByToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:constrainedByToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }

    static public String constrainsToHtmlForCreation (final HttpServletRequest httpServletRequest)
    {
    	String s = "";
    
    	// Start of user code "Init:constrainsToHtmlForCreation(...)"
    	// End of user code
    
    	s = s + "<label for=\"constrains\">constrains: </LABEL>";
    
    	// Start of user code "Mid:constrainsToHtmlForCreation(...)"
    	// End of user code
    
    	// Start of user code "Finalize:constrainsToHtmlForCreation(...)"
    	// End of user code
    
    	return s; 
    }


    public String titleToHtml()
    {
		String s = "";

		// Start of user code titletoHtml_init
		// End of user code

		s = s + "<label for=\"title\"><strong>title</strong>: </LABEL>";

		// Start of user code titletoHtml_mid
		// End of user code

		try {
				if (title == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + title.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code titletoHtml_finalize
		// End of user code

		return s; 
    }
    public String descriptionToHtml()
    {
		String s = "";

		// Start of user code descriptiontoHtml_init
		// End of user code

		s = s + "<label for=\"description\"><strong>description</strong>: </LABEL>";

		// Start of user code descriptiontoHtml_mid
		// End of user code

		try {
				if (description == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + description.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code descriptiontoHtml_finalize
		// End of user code

		return s; 
    }
    public String identifierToHtml()
    {
		String s = "";

		// Start of user code identifiertoHtml_init
		// End of user code

		s = s + "<label for=\"identifier\"><strong>identifier</strong>: </LABEL>";

		// Start of user code identifiertoHtml_mid
		// End of user code

		try {
				if (identifier == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + identifier.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code identifiertoHtml_finalize
		// End of user code

		return s; 
    }
    public String shortTitleToHtml()
    {
		String s = "";

		// Start of user code shortTitletoHtml_init
		// End of user code

		s = s + "<label for=\"shortTitle\"><strong>shortTitle</strong>: </LABEL>";

		// Start of user code shortTitletoHtml_mid
		// End of user code

		try {
				if (shortTitle == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + shortTitle.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code shortTitletoHtml_finalize
		// End of user code

		return s; 
    }
    public String subjectToHtml()
    {
		String s = "";

		// Start of user code subjecttoHtml_init
		// End of user code

		s = s + "<label for=\"subject\"><strong>subject</strong>: </LABEL>";

		// Start of user code subjecttoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<String> itr = subject.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
					s= s + itr.next().toString();
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code subjecttoHtml_finalize
		// End of user code

		return s; 
    }
    public String creatorToHtml()
    {
		String s = "";

		// Start of user code creatortoHtml_init
		// End of user code

		s = s + "<label for=\"creator\"><strong>creator</strong>: </LABEL>";

		// Start of user code creatortoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Person> itr = creator.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
						s = s + itr.next().toHtml(true);
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code creatortoHtml_finalize
		// End of user code

		return s; 
    }
    public String contributorToHtml()
    {
		String s = "";

		// Start of user code contributortoHtml_init
		// End of user code

		s = s + "<label for=\"contributor\"><strong>contributor</strong>: </LABEL>";

		// Start of user code contributortoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Person> itr = contributor.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
						s = s + itr.next().toHtml(true);
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code contributortoHtml_finalize
		// End of user code

		return s; 
    }
    public String createdToHtml()
    {
		String s = "";

		// Start of user code createdtoHtml_init
		// End of user code

		s = s + "<label for=\"created\"><strong>created</strong>: </LABEL>";

		// Start of user code createdtoHtml_mid
		// End of user code

		try {
				if (created == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + created.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code createdtoHtml_finalize
		// End of user code

		return s; 
    }
    public String modifiedToHtml()
    {
		String s = "";

		// Start of user code modifiedtoHtml_init
		// End of user code

		s = s + "<label for=\"modified\"><strong>modified</strong>: </LABEL>";

		// Start of user code modifiedtoHtml_mid
		// End of user code

		try {
				if (modified == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + modified.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code modifiedtoHtml_finalize
		// End of user code

		return s; 
    }
    public String typeToHtml()
    {
		String s = "";

		// Start of user code typetoHtml_init
		// End of user code

		s = s + "<label for=\"type\"><strong>type</strong>: </LABEL>";

		// Start of user code typetoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Type> itr = type.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
						s = s + itr.next().toHtml(true);
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code typetoHtml_finalize
		// End of user code

		return s; 
    }
    public String serviceProviderToHtml()
    {
		String s = "";

		// Start of user code serviceProvidertoHtml_init
		// End of user code

		s = s + "<label for=\"serviceProvider\"><strong>serviceProvider</strong>: </LABEL>";

		// Start of user code serviceProvidertoHtml_mid
		// End of user code

		try {
				if (serviceProvider == null) {
					s= s + "<em>null</em>";				
				}
				else {
					s= s + serviceProvider.toString();				
				}
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code serviceProvidertoHtml_finalize
		// End of user code

		return s; 
    }
    public String instanceShapeToHtml()
    {
		String s = "";

		// Start of user code instanceShapetoHtml_init
		// End of user code

		s = s + "<label for=\"instanceShape\"><strong>instanceShape</strong>: </LABEL>";

		// Start of user code instanceShapetoHtml_mid
		// End of user code

		try {
                    if (instanceShape.getValue() == null) {
                        s = s + "<em>null</em>";             
                    }
                    else {
                        s = s + instanceShape.getValue().toString();                
                    }


	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code instanceShapetoHtml_finalize
		// End of user code

		return s; 
    }
    public String usesToHtml()
    {
		String s = "";

		// Start of user code usestoHtml_init
		// End of user code

		s = s + "<label for=\"uses\"><strong>uses</strong>: </LABEL>";

		// Start of user code usestoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = uses.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code usestoHtml_finalize
		// End of user code

		return s; 
    }
    public String elaboratedByToHtml()
    {
		String s = "";

		// Start of user code elaboratedBytoHtml_init
		// End of user code

		s = s + "<label for=\"elaboratedBy\"><strong>elaboratedBy</strong>: </LABEL>";

		// Start of user code elaboratedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = elaboratedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code elaboratedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String elaboratesToHtml()
    {
		String s = "";

		// Start of user code elaboratestoHtml_init
		// End of user code

		s = s + "<label for=\"elaborates\"><strong>elaborates</strong>: </LABEL>";

		// Start of user code elaboratestoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = elaborates.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code elaboratestoHtml_finalize
		// End of user code

		return s; 
    }
    public String specifiedByToHtml()
    {
		String s = "";

		// Start of user code specifiedBytoHtml_init
		// End of user code

		s = s + "<label for=\"specifiedBy\"><strong>specifiedBy</strong>: </LABEL>";

		// Start of user code specifiedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = specifiedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code specifiedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String specifiesToHtml()
    {
		String s = "";

		// Start of user code specifiestoHtml_init
		// End of user code

		s = s + "<label for=\"specifies\"><strong>specifies</strong>: </LABEL>";

		// Start of user code specifiestoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = specifies.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code specifiestoHtml_finalize
		// End of user code

		return s; 
    }
    public String affectedByToHtml()
    {
		String s = "";

		// Start of user code affectedBytoHtml_init
		// End of user code

		s = s + "<label for=\"affectedBy\"><strong>affectedBy</strong>: </LABEL>";

		// Start of user code affectedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = affectedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code affectedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String trackedByToHtml()
    {
		String s = "";

		// Start of user code trackedBytoHtml_init
		// End of user code

		s = s + "<label for=\"trackedBy\"><strong>trackedBy</strong>: </LABEL>";

		// Start of user code trackedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = trackedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code trackedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String implementedByToHtml()
    {
		String s = "";

		// Start of user code implementedBytoHtml_init
		// End of user code

		s = s + "<label for=\"implementedBy\"><strong>implementedBy</strong>: </LABEL>";

		// Start of user code implementedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = implementedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code implementedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String validatedByToHtml()
    {
		String s = "";

		// Start of user code validatedBytoHtml_init
		// End of user code

		s = s + "<label for=\"validatedBy\"><strong>validatedBy</strong>: </LABEL>";

		// Start of user code validatedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = validatedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code validatedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String satisfiedByToHtml()
    {
		String s = "";

		// Start of user code satisfiedBytoHtml_init
		// End of user code

		s = s + "<label for=\"satisfiedBy\"><strong>satisfiedBy</strong>: </LABEL>";

		// Start of user code satisfiedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = satisfiedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code satisfiedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String satisfiesToHtml()
    {
		String s = "";

		// Start of user code satisfiestoHtml_init
		// End of user code

		s = s + "<label for=\"satisfies\"><strong>satisfies</strong>: </LABEL>";

		// Start of user code satisfiestoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = satisfies.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code satisfiestoHtml_finalize
		// End of user code

		return s; 
    }
    public String decomposedByToHtml()
    {
		String s = "";

		// Start of user code decomposedBytoHtml_init
		// End of user code

		s = s + "<label for=\"decomposedBy\"><strong>decomposedBy</strong>: </LABEL>";

		// Start of user code decomposedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = decomposedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code decomposedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String decomposesToHtml()
    {
		String s = "";

		// Start of user code decomposestoHtml_init
		// End of user code

		s = s + "<label for=\"decomposes\"><strong>decomposes</strong>: </LABEL>";

		// Start of user code decomposestoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = decomposes.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code decomposestoHtml_finalize
		// End of user code

		return s; 
    }
    public String constrainedByToHtml()
    {
		String s = "";

		// Start of user code constrainedBytoHtml_init
		// End of user code

		s = s + "<label for=\"constrainedBy\"><strong>constrainedBy</strong>: </LABEL>";

		// Start of user code constrainedBytoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = constrainedBy.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code constrainedBytoHtml_finalize
		// End of user code

		return s; 
    }
    public String constrainsToHtml()
    {
		String s = "";

		// Start of user code constrainstoHtml_init
		// End of user code

		s = s + "<label for=\"constrains\"><strong>constrains</strong>: </LABEL>";

		// Start of user code constrainstoHtml_mid
		// End of user code

		try {
		        s = s + "<ul>";
				Iterator<Link> itr = constrains.iterator();
				while(itr.hasNext()) {
					s = s + "<li>";
                            if (itr.next().getValue() == null) {
                                s= s + "<em>null</em>";             
                            }
                            else {
                                s = s + itr.next().getValue().toString();
                            }
					s = s + "</li>";
				}
		        s = s + "</ul>";
	    } catch (Exception e) {
	        e.printStackTrace();
	    }

		// Start of user code constrainstoHtml_finalize
		// End of user code

		return s; 
    }
}
